version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"

  test:
    build:
      context: .
    entrypoint: ["mvn"]
    command: ["test"]
    profiles:
      - test-only
